### ISSUE TITLE
SUPER ISSUE: Modify behavior of DeveloperDatabaseFactory

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat-framework#4672]
Todos los módulos de Developer Database Factory están trayendo las cosas como vienen de la base de datos, pero las columnas según el orden en la cual se agregan.
Por esta razón, los resultados entre lo almacenado y lo mostrado puede diferir.
### Ejemplo en el que muestra bien los resultados:

developer database factory table columns order
table x
columns
  cx1
  cx2
  cx3

base de datos info
cx1 = info1
cx2 = info2
cx3 = info3

shown info
cx1 = info1
cx2 = info2
cx3 = info3
### Ejemplo en el que muestra mal los resultados:

developer database factory table columns order
table x
columns
  cx3
  cx2
  cx1

base de datos info
cx1 = info1
cx2 = info2
cx3 = info3

shown info
cx3 = info1
cx2 = info2
cx1 = info3

Si tienen un rato, por favor, demosle bola, porque puede traernos muchos problemas a la hora de testear.

@furszy @acostarodrigo

**Comment by furszy** [comment]
@lnacosta  queres taguearlo un poco más al issue?

**Comment by lnacosta** [comment]
@furszy te jode ?

**Comment by lnacosta** [comment]
@furszy sacale los que consideres innecesarios o de más.

**Comment by lnacosta** [comment]
time out!
